export const ROLE_STORAGE = {
  ROLE: 'ROLE',
};
export const StorageConstants = {
  USER_DETAILS:'user_details',
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  MERCHANT_DETAILS: 'merchantDetails',
  BILLING_KEY_STATUS: 'billingKeyStatus',
  CUSTOM_CODE_MODE: 'CustomCodeMode',
  CUSTOM_CODE_TYPE: 'CustomCodeType',
  CUSTOM_CODES: 'CustomCodes',
  PRINT_MODE: 'CompleteConstant',
  DEVICE_UNIQUE_ID: 'deviceUniqueId',
  SELETED_BLE_PRINTER: 'SELETED_BLE',
  SELETED_USB_PRINTER: 'SELETED_USB',
  USB_PRINTER_LIST: 'USB_PRINTER_LIST',
  BLE_PRINTER_LIST: 'BLE_PRINTER_LIST',
  ALL_PRODUCTS: 'allProducts',
  ORDER_TYPES: 'orderTypes',
  IS_LOGGED_IN_FIRST_TIME: 'isLoggedInFirstTime',
  PAYMENT_MODE: 'paymentMode',
  IS_ESTIMATE_WITH_NO_ITEMS: 'IsEstimateWithNoItems',
  OFFLINE: 'offline',
  ORDER_LIST: 'orderList',
  PREVIEW_ID: 'previewId',
  PRINT_INFORMATION: 'PRINT_INFORMATION',
  OFFLINE_HOLD_ON_LIST: 'offlineHoldOnList',
  SELECTED_STORE_AND_TERMINAL: 'selectedStoreAndTerminal',
  ORDER_RESET_TIME: 'orderResetTime',
  SELECTED_DATES: 'selected_dates',
  STORES_FULL_DETAILS: 'storesFullDetails',
  VEHICLE_TYPES: 'vehicle_types',
  MALL_DETAILS:'mall_details'
};
