export const SuccessConstants = {
  STATUS_CHANGED: 'Product status changed',
  SAVE_SUCCESSFUL: 'Saved successfully',
  UPDATED_SUCCESSFULLY: 'Updated successfully',
  ADD_SUCCESSFUL: 'Added successfully',
  NUMBER_ADDED: 'Number added successfully!',
  ACCESS_GRANTED: 'Access granted',
  STAFF_ADDED: 'New Staff created successfully',
  TERMINAL_CREATED: 'New terminal created successfully',
  STORE_CREATED: 'New Store created successfully',
  MANAGER_ACCESS_CREATED: 'Manager access granted',
  SINGLE_MANAGER_ACCESS: 'Single manager access',
  ROLES_CHANGED_STAFF_TO_MANAGER: 'Role upgraded to manager successfully',
  DELETED_SUCCESSFUL: 'Deleted successfully',
  PASSWORD_UPDATED: 'Password updated successfully',
  ACCESS_REMOVED: 'Removed access successfully',
  LOGOUT: 'Logout successful',
  LOGIN: 'Login successful',
  COPIED: 'Copied',
  REGISTER: 'Register successfully',
  ADDON_UPDATED: 'Addon updated',
  ADDON_ADDED: 'Addon added',
  PRODUCT_UPDATED: 'Product updated',
  PRODUCT_ADDED: 'Product added',
  STOCK_UPDATED: 'Stock updated',
  EXPENSE_ADDED: 'Expense added',
  EXPENSE_UPDATED: 'Expense updated',
  ADDED_ESTIMATE_TEMPLATE: 'Added Estimate Template',
  UPDATED_ESTIMATE_TEMPLATE: 'Updated Estimate Template',
  ADDED_INVOICE_TEMPLATE: 'Added Invoice Template',
  UPDATED_INVOICE_TEMPLATE: 'Updated Invoice Template',
  ORDER_TYPE_TEXT: 'Order type changed successfully',
  COPY_CLIPBOARD: 'Copied to Clipboard',
  PAYMENT_IS_SUCCESSFUL: 'Payment is successful',
  HOLD_ADDED_SUCCESSFUL: 'Hold added successfully',
  HOLD_REMOVED_SUCCESSFUL: 'Hold removed successfully',
};
